/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/character.glb --types --shadows 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = '[保留アクション].002' | 'Idle.Save' | '[保留アクション].001' | 'Run.Save' | '[保留アクション]'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    球_1: THREE.SkinnedMesh
    球_2: THREE.SkinnedMesh
    球_3: THREE.SkinnedMesh
    球_4: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    マテリアル: THREE.MeshStandardMaterial
    Material: THREE.MeshBasicMaterial
    Cloth: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default React.forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>(function Model(props, ref) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/character.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <group name="アーマチュア" scale={0.868}>
          <primitive object={nodes.Root} />
          <group name="球">
            <skinnedMesh name="球_1" geometry={nodes.球_1.geometry} material={materials.Black} skeleton={nodes.球_1.skeleton} />
            <skinnedMesh name="球_2" geometry={nodes.球_2.geometry} material={materials.マテリアル} skeleton={nodes.球_2.skeleton} />
            <skinnedMesh name="球_3" geometry={nodes.球_3.geometry} material={materials.Material} skeleton={nodes.球_3.skeleton} />
            <skinnedMesh name="球_4" geometry={nodes.球_4.geometry} material={materials.Cloth} skeleton={nodes.球_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
});

useGLTF.preload('/models/character.glb')
